apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  labels:
    release: prometheus    # muy importante: debe coincidir con el label del Prometheus Operator
spec:
  selector:
    matchLabels:
      app: api-gateway
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
