apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
spec:
  destination:
    namespace: frontend
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: 'https://github.com/PaulaMilla/prueba_gps-deploy.git'
    targetRevision: HEAD
    path: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true