apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventarios-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventarios-service
  template:
    metadata:
      labels:
        app: inventarios-service
    spec:
      containers:
        - name: inventarios-service
          image: paulaveloso/inventarios-service:b383f8d
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db.default.svc.cluster.local:3306/sga_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
