apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: usuarios-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/PaulaMilla/prueba_gps-deploy.git'
    targetRevision: HEAD
    path: usuarios-service

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: usuarios

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
