apiVersion: apps/v1
kind: Deployment
metadata:
  name: usuarios-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usuarios-service
  template:
    metadata:
      labels:
        app: usuarios-service
    spec:
      containers:
        - name: usuarios-service
          image: paulaveloso/usuarios-service:0b7ff2f
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/sga_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
