apiVersion: v1
kind: Service
metadata:
  name: usuarios-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: usuarios-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
