apiVersion: v1
kind: Service
metadata:
  name: caja-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: caja-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080